I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    $ rpy.history_length(1)
  File "game/script.rpy", line 16, in <module>
    $ rpy.history_length(1)
AttributeError: module 'renpy' has no attribute 'history_length'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    $ rpy.history_length(1)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    $ rpy.history_length(1)
AttributeError: module 'renpy' has no attribute 'history_length'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
AAA 0.0.3.25
Tue Dec 20 16:57:23 2022
