I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 64, in script call
    call neg1
  File "game/sxA20.rpy", line 155, in script
    "Number of endings completed: [gameState] "
KeyError: 'gameState'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 64, in script call
    call neg1
  File "game/sxA20.rpy", line 155, in script
    "Number of endings completed: [gameState] "
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\character.py", line 1253, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\character.py", line 1172, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\character.py", line 1152, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'gameState'

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
AAA 0.0.2.6.9
Sat Dec  3 17:00:10 2022
